# -- Define this spec locally and pass it to below command if you want to setup Grafana/Prometheus along with serviceMonitor:
# helm install my-cadence cadence/cadence -n <namepspace> -f <path to custom_values.yaml>

metrics:
  enabled: true
  port: 9090
  portName: metrics

  serviceMonitor:
    enabled: true
    # Replace with the namespace where Prometheus is deployed
    namespace: ""
    namespaceSelector:
       # Ensure this matches Prometheus's namespace
      matchNames:
        - 
    scrapeInterval: 10s
    additionalLabels:
       # Ensure this matches Prometheus's Helm release name
      release: my-prometheus
    annotations: {}
    jobLabel: "app.kubernetes.io/name"
    targetLabels:
      - app.kubernetes.io/name
    relabelings: []
    metricRelabelings: []